#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
ENV_EXAMPLE="$ROOT_DIR/.env.example"
APP_NAME="meteora-screening-bot"

prompt() {
  local label="$1"
  local default="${2:-}"
  local secret="${3:-false}"
  local value=""

  if [[ "$secret" == "true" ]]; then
    if [[ -n "$default" ]]; then
      read -r -s -p "$label [$default]: " value
    else
      read -r -s -p "$label: " value
    fi
    echo
  else
    if [[ -n "$default" ]]; then
      read -r -p "$label [$default]: " value
    else
      read -r -p "$label: " value
    fi
  fi

  if [[ -z "$value" ]]; then
    value="$default"
  fi

  printf '%s' "$value"
}

require_cmd() {
  local cmd="$1"
  local help_msg="$2"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: '$cmd' tidak ditemukan. $help_msg"
    exit 1
  fi
}

echo "== Meteora Screening Bot Installer =="
echo

require_cmd node "Install Node.js 18+ dulu, lalu jalankan installer ini lagi."
require_cmd npm "Install npm dulu, lalu jalankan installer ini lagi."

NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if [[ "$NODE_MAJOR" -lt 18 ]]; then
  echo "Error: Node.js 18+ diperlukan. Versi sekarang: $(node -v)"
  exit 1
fi

if [[ ! -f "$ENV_EXAMPLE" ]]; then
  echo "Error: .env.example tidak ditemukan di $ROOT_DIR"
  exit 1
fi

echo "Project directory: $ROOT_DIR"
echo
echo "Installer ini akan:"
echo "1. Mengisi file .env"
echo "2. Install dependency npm"
echo "3. Install pm2 jika belum ada"
echo "4. Menjalankan screening bot via pm2"
echo

echo "-- App Settings --"
APP_TIMEZONE="$(prompt "APP_TIMEZONE" "Asia/Jakarta")"
APP_LOG_LEVEL="$(prompt "APP_LOG_LEVEL" "info")"
APP_POLL_INTERVAL_MINUTES="$(prompt "APP_POLL_INTERVAL_MINUTES" "15")"
APP_MAX_CANDIDATES="$(prompt "APP_MAX_CANDIDATES" "80")"
APP_SHORTLIST_LIMIT="$(prompt "APP_SHORTLIST_LIMIT" "10")"

echo
echo "-- Meteora Filters --"
METEORA_CATEGORY="$(prompt "METEORA_CATEGORY (top/new/trending)" "top")"
METEORA_DISCOVERY_TIMEFRAME="$(prompt "METEORA_DISCOVERY_TIMEFRAME" "24h")"
METEORA_MIN_MARKET_CAP_USD="$(prompt "METEORA_MIN_MARKET_CAP_USD" "250000")"
METEORA_MAX_MARKET_CAP_USD="$(prompt "METEORA_MAX_MARKET_CAP_USD" "50000000")"
METEORA_MIN_TOKEN_AGE_HOURS="$(prompt "METEORA_MIN_TOKEN_AGE_HOURS" "2")"
METEORA_MIN_HOLDERS="$(prompt "METEORA_MIN_HOLDERS" "500")"
METEORA_MIN_VOLUME_24H_USD="$(prompt "METEORA_MIN_VOLUME_24H_USD" "1000000")"
METEORA_MIN_VOLUME_1H_USD="$(prompt "METEORA_MIN_VOLUME_1H_USD" "1000")"
METEORA_MIN_TVL_USD="$(prompt "METEORA_MIN_TVL_USD" "10000")"
METEORA_MIN_FEE_TVL_RATIO_24H="$(prompt "METEORA_MIN_FEE_TVL_RATIO_24H" "50")"
METEORA_MIN_BASE_FEE_PCT="$(prompt "METEORA_MIN_BASE_FEE_PCT" "2")"
METEORA_MAX_BASE_FEE_PCT="$(prompt "METEORA_MAX_BASE_FEE_PCT" "10")"
METEORA_REQUIRED_BIN_STEP="$(prompt "METEORA_REQUIRED_BIN_STEP" "100")"
METEORA_REQUIRE_BOTH_VERIFIED="$(prompt "METEORA_REQUIRE_BOTH_VERIFIED" "true")"

echo
echo "-- Jupiter Filters --"
JUPITER_API_KEY="$(prompt "JUPITER_API_KEY (optional, enter untuk kosong)" "" true)"
JUPITER_REQUIRE_VERIFIED="$(prompt "JUPITER_REQUIRE_VERIFIED" "true")"
JUPITER_MIN_ORGANIC_SCORE="$(prompt "JUPITER_MIN_ORGANIC_SCORE" "60")"
JUPITER_MAX_TOP10_HOLDERS_PCT="$(prompt "JUPITER_MAX_TOP10_HOLDERS_PCT" "30")"
JUPITER_REQUIRE_MINT_AUTHORITY_DISABLED="$(prompt "JUPITER_REQUIRE_MINT_AUTHORITY_DISABLED" "true")"
JUPITER_REQUIRE_FREEZE_AUTHORITY_DISABLED="$(prompt "JUPITER_REQUIRE_FREEZE_AUTHORITY_DISABLED" "true")"
JUPITER_MIN_GLOBAL_FEES_SOL="$(prompt "JUPITER_MIN_GLOBAL_FEES_SOL" "30")"

echo
echo "-- OKX Filters --"
OKX_MAX_BUNDLE_PCT="$(prompt "OKX_MAX_BUNDLE_PCT" "30")"
OKX_MAX_SUSPICIOUS_PCT="$(prompt "OKX_MAX_SUSPICIOUS_PCT" "10")"
OKX_REQUIRE_NOT_WASH="$(prompt "OKX_REQUIRE_NOT_WASH" "true")"

echo
echo "-- Rugcheck Filters --"
RUGCHECK_MAX_SCORE="$(prompt "RUGCHECK_MAX_SCORE" "30")"
RUGCHECK_MAX_WARN_RISKS="$(prompt "RUGCHECK_MAX_WARN_RISKS" "1")"
RUGCHECK_REQUIRE_ZERO_DANGER_RISKS="$(prompt "RUGCHECK_REQUIRE_ZERO_DANGER_RISKS" "true")"
RUGCHECK_REQUIRE_NOT_HONEYPOT="$(prompt "RUGCHECK_REQUIRE_NOT_HONEYPOT" "true")"
RUGCHECK_REQUIRE_IMMUTABLE_METADATA="$(prompt "RUGCHECK_REQUIRE_IMMUTABLE_METADATA" "true")"

echo
echo "-- Telegram (optional) --"
TELEGRAM_BOT_TOKEN="$(prompt "TELEGRAM_BOT_TOKEN (optional, enter untuk kosong)" "" true)"
TELEGRAM_CHAT_ID="$(prompt "TELEGRAM_CHAT_ID (optional, enter untuk kosong)" "")"
TELEGRAM_NOTIFY_STARTUP="$(prompt "TELEGRAM_NOTIFY_STARTUP" "true")"
TELEGRAM_NOTIFY_RESULTS="$(prompt "TELEGRAM_NOTIFY_RESULTS" "true")"
TELEGRAM_NOTIFY_EMPTY="$(prompt "TELEGRAM_NOTIFY_EMPTY" "true")"
TELEGRAM_NOTIFY_ERRORS="$(prompt "TELEGRAM_NOTIFY_ERRORS" "true")"

cat > "$ENV_FILE" <<EOF
# Generated by install.sh

APP_NAME=Meteora Screening Bot
APP_TIMEZONE=$APP_TIMEZONE
APP_LOG_LEVEL=$APP_LOG_LEVEL
APP_RUN_ONCE=false
APP_POLL_INTERVAL_MINUTES=$APP_POLL_INTERVAL_MINUTES
APP_MAX_CANDIDATES=$APP_MAX_CANDIDATES
APP_SHORTLIST_LIMIT=$APP_SHORTLIST_LIMIT

METEORA_POOL_DISCOVERY_BASE=https://pool-discovery-api.datapi.meteora.ag
METEORA_DLMM_BASE=https://dlmm.datapi.meteora.ag
METEORA_CATEGORY=$METEORA_CATEGORY
METEORA_DISCOVERY_TIMEFRAME=$METEORA_DISCOVERY_TIMEFRAME
METEORA_MIN_MARKET_CAP_USD=$METEORA_MIN_MARKET_CAP_USD
METEORA_MAX_MARKET_CAP_USD=$METEORA_MAX_MARKET_CAP_USD
METEORA_MIN_TOKEN_AGE_HOURS=$METEORA_MIN_TOKEN_AGE_HOURS
METEORA_MIN_HOLDERS=$METEORA_MIN_HOLDERS
METEORA_MIN_VOLUME_24H_USD=$METEORA_MIN_VOLUME_24H_USD
METEORA_MIN_VOLUME_1H_USD=$METEORA_MIN_VOLUME_1H_USD
METEORA_MIN_TVL_USD=$METEORA_MIN_TVL_USD
METEORA_MIN_FEE_TVL_RATIO_24H=$METEORA_MIN_FEE_TVL_RATIO_24H
METEORA_MIN_BASE_FEE_PCT=$METEORA_MIN_BASE_FEE_PCT
METEORA_MAX_BASE_FEE_PCT=$METEORA_MAX_BASE_FEE_PCT
METEORA_REQUIRED_BIN_STEP=$METEORA_REQUIRED_BIN_STEP
METEORA_REQUIRE_BOTH_VERIFIED=$METEORA_REQUIRE_BOTH_VERIFIED

JUPITER_API_BASE=https://api.jup.ag
JUPITER_DATAPI_BASE=https://datapi.jup.ag/v1
JUPITER_API_KEY=$JUPITER_API_KEY
JUPITER_REQUIRE_VERIFIED=$JUPITER_REQUIRE_VERIFIED
JUPITER_MIN_ORGANIC_SCORE=$JUPITER_MIN_ORGANIC_SCORE
JUPITER_MAX_TOP10_HOLDERS_PCT=$JUPITER_MAX_TOP10_HOLDERS_PCT
JUPITER_REQUIRE_MINT_AUTHORITY_DISABLED=$JUPITER_REQUIRE_MINT_AUTHORITY_DISABLED
JUPITER_REQUIRE_FREEZE_AUTHORITY_DISABLED=$JUPITER_REQUIRE_FREEZE_AUTHORITY_DISABLED
JUPITER_MIN_GLOBAL_FEES_SOL=$JUPITER_MIN_GLOBAL_FEES_SOL

OKX_BASE=https://web3.okx.com
OKX_MAX_BUNDLE_PCT=$OKX_MAX_BUNDLE_PCT
OKX_MAX_SUSPICIOUS_PCT=$OKX_MAX_SUSPICIOUS_PCT
OKX_REQUIRE_NOT_WASH=$OKX_REQUIRE_NOT_WASH

RUGCHECK_API_BASE=https://api.rugcheck.xyz/v1
RUGCHECK_MAX_SCORE=$RUGCHECK_MAX_SCORE
RUGCHECK_MAX_WARN_RISKS=$RUGCHECK_MAX_WARN_RISKS
RUGCHECK_REQUIRE_ZERO_DANGER_RISKS=$RUGCHECK_REQUIRE_ZERO_DANGER_RISKS
RUGCHECK_REQUIRE_NOT_HONEYPOT=$RUGCHECK_REQUIRE_NOT_HONEYPOT
RUGCHECK_REQUIRE_IMMUTABLE_METADATA=$RUGCHECK_REQUIRE_IMMUTABLE_METADATA

TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
TELEGRAM_NOTIFY_STARTUP=$TELEGRAM_NOTIFY_STARTUP
TELEGRAM_NOTIFY_RESULTS=$TELEGRAM_NOTIFY_RESULTS
TELEGRAM_NOTIFY_EMPTY=$TELEGRAM_NOTIFY_EMPTY
TELEGRAM_NOTIFY_ERRORS=$TELEGRAM_NOTIFY_ERRORS
TELEGRAM_TIMEOUT_MS=15000
TELEGRAM_RETRY_COUNT=1
EOF

echo
echo "File .env berhasil dibuat."

cd "$ROOT_DIR"

echo
echo "Installing npm dependencies..."
npm install

if ! command -v pm2 >/dev/null 2>&1; then
  echo
  echo "pm2 belum ada. Installing pm2 globally..."
  npm install -g pm2
fi

echo
echo "Restarting pm2 app: $APP_NAME"
pm2 delete "$APP_NAME" >/dev/null 2>&1 || true
pm2 start ecosystem.config.cjs
pm2 save

echo
echo "Install selesai."
echo
echo "Perintah berguna:"
echo "  pm2 status"
echo "  pm2 logs $APP_NAME"
echo "  pm2 restart $APP_NAME"
echo "  pm2 stop $APP_NAME"
